"env": "Minigrid"
# "name": "MiniGrid-MortarAB-v0"
"name": "MiniGrid-MortarB-v0"
"gamma": 0.99
"lamda": 0.95
"updates": 3300
"epochs": 6
"n_workers": 16
"worker_steps": 512
"n_mini_batch": 8
"value_loss_coefficient": 0.25
"hidden_layer_size": 512
"transformer":
    "num_blocks": 1
    "embed_dim": 512
    "num_heads": 4
    "memory_length": 32
    "positional_encoding": ""
    "layer_norm": "pre"
"learning_rate_schedule":
    "initial": 3.25e-4
    "final": 1.0e-4
    "power": 1.0
    "max_decay_steps": 3300
"beta_schedule":
    "initial": 0.01
    "final": 0.001
    "power": 1.0
    "max_decay_steps": 3300
"clip_range_schedule":
    "initial": 0.2
    "final": 0.2
    "power": 1.0
    "max_decay_steps": 3300